#pragma once

#include <cstdint>

namespace engine::utils::enums::input {
    enum MouseButton : uint8_t {
        MOUSE_NONE,
        MOUSE_LEFT,
        MOUSE_MIDDLE,
        MOUSE_RIGHT,
        MOUSE_EXTRA1,
        MOUSE_EXTRA2
    };

    enum PadButton : uint32_t {
        PAD_BUTTON_UNKNOWN = 0,
        PAD_BUTTON_A = (1 << 0),
        PAD_BUTTON_B = (1 << 1),
        PAD_BUTTON_X = (1 << 2),
        PAD_BUTTON_Y = (1 << 3),
        PAD_BUTTON_L = (1 << 4),
        PAD_BUTTON_R = (1 << 5),
        PAD_BUTTON_L2 = (1 << 6),
        PAD_BUTTON_R2 = (1 << 7),
        PAD_BUTTON_L3 = (1 << 8),
        PAD_BUTTON_R3 = (1 << 9),
        PAD_BUTTON_STICK_L = (1 << 10),
        PAD_BUTTON_STICK_R = (1 << 11),
        PAD_BUTTON_DPAD_UP = (1 << 12),
        PAD_BUTTON_DPAD_DOWN = (1 << 13),
        PAD_BUTTON_DPAD_LEFT = (1 << 14),
        PAD_BUTTON_DPAD_RIGHT = (1 << 15),
        PAD_BUTTON_SWITCH_PLUS = (1 << 16),
        PAD_BUTTON_SWITCH_MINUS= (1 << 17),
    };

    enum KeyType : uint16_t {
        KEY_UNKNOWN,
        KEY_0 = 0x30,
        KEY_1,
        KEY_2,
        KEY_3,
        KEY_4,
        KEY_5,
        KEY_6,
        KEY_7,
        KEY_8,
        KEY_9,
        KEY_A = 0x41,
        KEY_B,
        KEY_C,
        KEY_D,
        KEY_E,
        KEY_F,
        KEY_G,
        KEY_H,
        KEY_I,
        KEY_J,
        KEY_K,
        KEY_L,
        KEY_M,
        KEY_N,
        KEY_O,
        KEY_P,
        KEY_Q,
        KEY_R,
        KEY_S,
        KEY_T,
        KEY_U,
        KEY_V,
        KEY_W,
        KEY_X,
        KEY_Y,
        KEY_Z,
        KEY_OS_KEY,
        KEY_NUMPAD_0 = 0x60,
        KEY_NUMPAD_1,
        KEY_NUMPAD_2,
        KEY_NUMPAD_3,
        KEY_NUMPAD_4,
        KEY_NUMPAD_5,
        KEY_NUMPAD_6,
        KEY_NUMPAD_7,
        KEY_NUMPAD_8,
        KEY_NUMPAD_9,
        KEY_MULTIPLY,
        KEY_ADD,
        KEY_SEPARATOR,
        KEY_SUBTRACT,
        KEY_DECIMAL,
        KEY_DIVIDE,
        KEY_F1,
        KEY_F2,
        KEY_F3,
        KEY_F4,
        KEY_F5,
        KEY_F6,
        KEY_F7,
        KEY_F8,
        KEY_F9,
        KEY_F10,
        KEY_F11,
        KEY_F12,
        KEY_F13,
        KEY_F14,
        KEY_F15,
        KEY_F16,
        KEY_F17,
        KEY_F18,
        KEY_F19,
        KEY_F20,
        KEY_F21,
        KEY_F22,
        KEY_F23,
        KEY_F24,
        KEY_SPACE
    };
}